circular_buffer:
	make -f circular_buffer.mk

input_buffer:
	make -f input_buffer.mk

input_port:
	make -f input_port.mk

rc_unit:
	make -f rc_unit.mk

verdi:
	make -f mesh.mk verdi

clean:
	make -f rc_unit.mk clean
