vc_allocator:
	make -f vc_allocator.mk

round_robin_arbiter:
	make -f round_robin_arbiter.mk

separable_input_first_allocator:
	make -f separable_input_first_allocator.mk

switch_allocator:
	make -f switch_allocator.mk

verdi:
	make -f mesh.mk verdi

clean:
	make -f separable_input_first_allocator.mk clean
